### ISSUE TITLE
Possibly invalid exports

### ISSUE THREAD

**Issue by Merri** [ark120202/find-steam-app#1]
When using Node with `--experimental-modules` using this library like this does not work:

```
import { findSteamAppById } from 'find-steam-app'
         ^^^^^^^^^^^^^^^^
SyntaxError: The requested module 'find-steam-app' does not provide an export named 'findSteamAppById'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:79:21)
```

However importing without destructuring works ok:

```js
import findSteamApp from 'find-steam-app'
// this is fine
const pathname = await findSteamApp.findSteamAppById(8930)
```

This issue is probably caused by this line in index.ts:

```
export { AppManifest, findSteam };
```

Which maybe exports `default` as an object and then causes all the other exports in the file to this object in `default` instead of exposing them as named items. However I'm not familiar with how TypeScript handles import and export.

**Comment by ark120202** [comment]
That's because ESM exports are compiled to commonjs (https://unpkg.com/find-steam-app@1.0.1/lib/index.js) with a special `__esModule` flag, so it correctly works when used with any popular transpiler, but node's implementation allows to import commonjs modules only with default import - https://nodejs.org/api/esm.html#esm_interop_with_existing_modules and named imports may be used only when importing `.mjs` files (named imports aren't the same as object destructuring). I guess it would make sense to remove not-yet-standardized in node syntax from the example.
